### ISSUE TITLE
update für Version 9

### ISSUE THREAD

**Issue by dietmarwalser** [Sethorax/typo3-dcp#3]
Hallo Chrisxf,
gibt es bei Dir einen Plan ein Update für die Version 9 anzugehen?
Habe keinen anderen Plugin mit ähnlicher Funktionalität gefunden, und es wäre grandios.
Grüße
Dietmar

**Comment by chfoidl** [comment]
Hallo Dietmar,

habe gerade das Update 1.2.0 veröffentlicht.
Diese Version behebt kleine Bugs und kommt mit Unterstützung für Typo3 9.

**Comment by dietmarwalser** [comment]
Hallo Chris,
danke für die rasante Anlieferung... es schaut so aus, als ob es wieder klappt.
Vielen Dank!!
